# Generated by Django 4.2.13 on 2024-07-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryphotomodel",
            name="photo",
            field=models.ImageField(upload_to="gallery/2024/7/"),
        ),
    ]
