# Generated by Django 4.2.13 on 2024-06-26 00:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='location_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='location_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='location_text_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
