# Generated by Django 4.2.13 on 2024-07-04 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontactmodel",
            name="is_contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usercontactmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userContacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
