# Generated by Django 4.2.13 on 2024-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField()),
                ('free_count', models.BigIntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('status', models.TextField(verbose_name='status')),
                ('status_ru', models.TextField(null=True, verbose_name='status')),
                ('status_uz', models.TextField(null=True, verbose_name='status')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('product_price', models.BigIntegerField()),
                ('total_price', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
