# Generated by Django 4.2.13 on 2024-06-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status_uz',
            field=models.TextField(null=True),
        ),
    ]
